### ISSUE TITLE
typo in cordova readme

### ISSUE THREAD

**Issue by smiklosovic** [jboss-mobile/unified-push-helloworld#17]
"Cordova" gives me the following, it should be "cordova" instead.

smikloso@localhost cordova]$ npm install -g Cordova
npm ERR! 404 404 Not Found: Cordova
npm ERR! 404 
npm ERR! 404 'Cordova' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.10.0-229.7.2.el7.x86_64
npm ERR! command "/home/smikloso/devel/node/bin/node" "/home/smikloso/devel/node/bin/npm" "install" "-g" "Cordova"
npm ERR! cwd /home/smikloso/dev/AG/unified-push-helloworld/cordova
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/smikloso/dev/AG/unified-push-helloworld/cordova/npm-debug.log
npm ERR! not ok code 0

**Comment by matzew** [comment]
@smiklosovic can you open a JIRA ?

**Comment by danielpassos** [comment]
Or send a PR ;)

**Comment by matzew** [comment]
+1000 :smile:

On Wed, Jul 22, 2015 at 5:16 PM, Daniel Passos notifications@github.com
wrote:

> Or send a PR ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jboss-mobile/unified-push-helloworld/issues/17#issuecomment-123755363
> .

## 

Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by smiklosovic** [comment]
i was in a hurry :)

**Comment by edewit** [comment]
here you go https://github.com/jboss-mobile/unified-push-helloworld/pull/18
