### ISSUE TITLE
how can set Alias when register the app on aerogear

### ISSUE THREAD

**Issue by pawarlalit29** [jboss-mobile/unified-push-helloworld#24]
how can set Alias when register the app on aerogear
what was the steps to getDeviceToken()

**Comment by danielpassos** [comment]
@pawarlalit29 It depends what platform are you using? Android, Cordova, iOS?

**Comment by pawarlalit29** [comment]
In Android ,
And how can I get token

**Comment by danielpassos** [comment]
@pawarlalit29 What token are you talking about?

**Comment by pawarlalit29** [comment]
It's gcm token

**Comment by danielpassos** [comment]
You can use config to setAlias

```
RegistrarManager.config("myPushRegistar", AeroGearGCMPushConfiguration.class)
                .setPushServerURI(new URI(UNIFIED_PUSH_URL))
                .setSenderIds(GCM_SENDER_ID)
                .setVariantID(VARIANT_ID)
                .setSecret(SECRET)
                .setAlias("myAlias")
                .asRegistrar();
```

**Comment by danielpassos** [comment]
@pawarlalit29 Not sure _why_ you need GCM token

**Comment by pawarlalit29** [comment]
Thanks ,
We maintain that token n our app

**Comment by danielpassos** [comment]
@pawarlalit29 Still don't understand **why** you need that. Anyway, AeroGear don't expose that.

**Comment by pawarlalit29** [comment]
We used that token to prevent the duplicate notification message when reinstalling the app

**Comment by danielpassos** [comment]
@pawarlalit29 If you are receiving duplicate message when reinstall the app something is wrong. Open a JIRA for us with the step by step to reproduce it.

Please, don't forget to inform what AGDROID and UPS version you are using.

https://issues.jboss.org/projects/AGDROID

**Comment by pawarlalit29** [comment]
That time new token generated ,and previous one is also active so when we send the message to particular alias ,that time same aliase with multiple token

**Comment by pawarlalit29** [comment]
If previous token is active then gcm send notification to both active token

**Comment by pawarlalit29** [comment]
Thanks ,

**Comment by danielpassos** [comment]
@pawarlalit29 IMO the old will be invalidated by GCM and we need to automatic stop to send message for that. Please, fire a JIRA for that problem or please, move that conversation to the [AeroGear Mailing lint](http://aerogear-dev.1069024.n5.nabble.com/)
