### ISSUE TITLE
NullPointerExeption

### ISSUE THREAD

**Issue by boberski666** [jboss-mobile/unified-push-helloworld#25]
Hi,
I checkout and run android app from https://github.com/jboss-mobile/unified-push-helloworld/tree/master/android. When I send push and app is in background I get bar notyfication, and that is good :) but when I click on in I get:

> 02-08 15:01:02.811 9756-9756/org.jboss.aerogear.unifiedpush.helloworld E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{org.jboss.aerogear.unifiedpush.helloworld/org.jboss.aerogear.unifiedpush.helloworld.activities.MessagesActivity}: java.lang.NullPointerException
>                                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2355)
>                                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
>                                                                                              at android.app.ActivityThread.access$600(ActivityThread.java:151)
>                                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1335)
>                                                                                              at android.os.Handler.dispatchMessage(Handler.java:99)
>                                                                                              at android.os.Looper.loop(Looper.java:155)
>                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5520)
>                                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                                              at java.lang.reflect.Method.invoke(Method.java:511)
>                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
>                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
>                                                                                              at dalvik.system.NativeStart.main(Native Method)
>                                                                                           Caused by: java.lang.NullPointerException
>                                                                                              at org.jboss.aerogear.unifiedpush.helloworld.HelloWorldApplication.sendMetric(HelloWorldApplication.java:54)
>                                                                                              at org.jboss.aerogear.unifiedpush.helloworld.activities.MessagesActivity.onCreate(MessagesActivity.java:49)
>                                                                                              at android.app.Activity.performCreate(Activity.java:5066)
>                                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101)
>                                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
>                                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391) 
>                                                                                              at android.app.ActivityThread.access$600(ActivityThread.java:151) 
>                                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1335) 
>                                                                                              at android.os.Handler.dispatchMessage(Handler.java:99) 
>                                                                                              at android.os.Looper.loop(Looper.java:155) 
>                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5520) 
>                                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
>                                                                                              at java.lang.reflect.Method.invoke(Method.java:511) 
>                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029) 
>                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796) 
>                                                                                              at dalvik.system.NativeStart.main(Native Method)

**Comment by MaikCL** [comment]
Clone repo and tested today, same issue.
Launch App, close from system tray and launch the notification, when te notification appear on system bar, and open the notification, the app crash with same Logcat

**Comment by danielpassos** [comment]
Can you open a jira with the steps to reproduce that? 

https://issues.jboss.org/projects/AGDROID
