### ISSUE TITLE
Failed to resolved

### ISSUE THREAD

**Issue by boberski666** [jboss-mobile/unified-push-helloworld#27]
When I addd this to build.gradle and do sync:

compile 'org.jboss.aerogear:aerogear-android-core:3.0.0-SNAPSHOT'
compile 'org.jboss.aerogear:aerogear-android-pipe:3.0.0-SNAPSHOT'
compile 'org.jboss.aerogear:aerogear-android-push:3.0.0-SNAPSHOT'

I get:
Error:(30, 13) Failed to resolve: org.jboss.aerogear:aerogear-android-push:3.0.0-SNAPSHOT
Error:(28, 13) Failed to resolve: org.jboss.aerogear:aerogear-android-core:3.0.0-SNAPSHOT
Error:(30, 13) Failed to resolve: org.jboss.aerogear:aerogear-android-push:3.0.0-SNAPSHOT

**Comment by danielpassos** [comment]
Hi @aderal000 

These snapshots are not published in anywhere, you will need to build that libraries locally from Github source.

@matzew, @secondsun should we revert the https://github.com/jboss-mobile/unified-push-helloworld/pull/26 merger from master and move it for a branch?

**Comment by secondsun** [comment]
I've reverted the merge and pushed master to the https://github.com/jboss-mobile/unified-push-helloworld/tree/gcm3 branch.

**Comment by matzew** [comment]
Sorry for that, @aderal000
